Vinay, Bindu | BAH-872 | adding dummy class to fix IT tests
Bahmni/openmrs-module-bahmni.ie.apps pull request #3
Opened 2019-08-12 17:02 UTC by binduak

2019-08-29 10:53 UTC, bsneha90 commented
The file should be added to 'omod/src/test/java/org/openmrs/', please move it.

2019-08-29 10:54 UTC, bsneha90 requested changes
The file should be added to 'omod/src/test/java/org/openmrs/', please move it.

2019-08-30 07:13 UTC, binduak commented
@bsneha90 moved the file to test folder

2019-08-30 10:17 UTC, bsneha90 approved these changes

2019-08-30 10:17 UTC, merged