#BAH-866 | Translations to be copied from one version to next version
Bahmni/openmrs-module-bahmni.ie.apps pull request #4
Opened 2019-08-30 10:55 UTC by AlekhyaYalla

Add reference version to get the translations.

Bahmni jira link:
https://bahmni.atlassian.net/browse/BAH-866

2019-09-03 04:14 UTC, bsneha90 requested changes

2019-09-03 04:14 UTC, bsneha90 commented on omod/src/main/java/org/openmrs/module/bahmni/ie/apps/service/impl/BahmniFormTranslationServiceImpl.java
> +            if (formVersion > 0 && isNotEmpty(refVersion)) {
abstract out a method/constant to mention what are we trying to check when we say "formVersion >0"

2019-09-03 04:14 UTC, bsneha90 commented on omod/src/main/java/org/openmrs/module/bahmni/ie/apps/service/impl/BahmniFormTranslationServiceImpl.java
> +        // Controls can be either CONCEPTS or LABELS`
can we remove this comment?

2019-09-03 04:14 UTC, bsneha90 commented on omod/src/main/java/org/openmrs/module/bahmni/ie/apps/service/impl/BahmniFormTranslationServiceImpl.java
> +                JSONObject previousTranslationsJson = getTranslations(new File(getFileName(formName, refVersion)));
can we retain the word reference instead of previous?

2019-09-03 04:14 UTC, bsneha90 commented on omod/src/main/java/org/openmrs/module/bahmni/ie/apps/service/impl/BahmniFormTranslationServiceImpl.java
> +    private void updatePreviousVersionLocaleTranslations(FormTranslation translation, JSONObject translationsJson,
this method is updating the values of currentControls, not previousVersionLocale, can we have a more appropriate name?

2019-09-03 05:59 UTC, AlekhyaYalla commented on omod/src/main/java/org/openmrs/module/bahmni/ie/apps/service/impl/BahmniFormTranslationServiceImpl.java
> +            if (formVersion > 0 && isNotEmpty(refVersion)) {
'formHaveRefVersion' does this constant works?

2019-09-03 06:00 UTC, AlekhyaYalla commented on omod/src/main/java/org/openmrs/module/bahmni/ie/apps/service/impl/BahmniFormTranslationServiceImpl.java
> +                JSONObject previousTranslationsJson = getTranslations(new File(getFileName(formName, refVersion)));
Yes, that works. modifying the same

2019-09-03 06:09 UTC, AlekhyaYalla commented on omod/src/main/java/org/openmrs/module/bahmni/ie/apps/service/impl/BahmniFormTranslationServiceImpl.java
> +    private void updatePreviousVersionLocaleTranslations(FormTranslation translation, JSONObject translationsJson,
'updateTranslationsWithRefVersion' does this name works?

2019-09-06 10:46 UTC, bsneha90 commented on omod/src/main/java/org/openmrs/module/bahmni/ie/apps/service/impl/BahmniFormTranslationServiceImpl.java
> +    private void updatePreviousVersionLocaleTranslations(FormTranslation translation, JSONObject translationsJson,
yes

2019-09-06 10:47 UTC, bsneha90 commented on omod/src/main/java/org/openmrs/module/bahmni/ie/apps/service/impl/BahmniFormTranslationServiceImpl.java
> +            if (formVersion > 0 && isNotEmpty(refVersion)) {
ok, add a test for it as well.

2019-09-09 06:52 UTC, AlekhyaYalla commented on omod/src/main/java/org/openmrs/module/bahmni/ie/apps/service/impl/BahmniFormTranslationServiceImpl.java
> +            if (formVersion > 0 && isNotEmpty(refVersion)) {
done @bsneha90

2019-09-11 08:46 UTC, bsneha90 approved these changes

2019-09-11 09:45 UTC, merged